services:
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    container_name: cupid-mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb_volumes/data:/data/db
      - ./mongodb_volumes/config:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
